// packages/sdk-svelte/src/lib/ZitadelSession.svelte
<script lang="ts">
  import '@zitadel/components';
  import type { ZitadelSession as ZitadelSessionElement } from '@zitadel/components';

  import type { ZitadelSessionProps, ZitadelContinueDetail, ZitadelSignoutDetail } from './types';

  let {
    project,
    projectId,
    proxyPath,
    continueUrl,
    postSignOutUrl,
    heading,
    continueLabel,
    logoutLabel,
    onContinue,
    onSignout,
  }: ZitadelSessionProps = $props();

  let el: ZitadelSessionElement | undefined = $state();

  /**
   * Returns the underlying `<zitadel-session>` custom element, or `undefined`
   * before the component has mounted. Exposed as a component method, reachable
   * from a parent via `bind:this` — the Svelte 5 analogue of a React `ref`.
   */
  export function getElement(): ZitadelSessionElement | undefined {
    return el;
  }

  $effect(() => {
    const node = el;
    if (!node) {
      return;
    }
    const onContinueEvent = (event: Event): void =>
      onContinue?.((event as CustomEvent<ZitadelContinueDetail>).detail);
    const onSignoutEvent = (event: Event): void =>
      onSignout?.((event as CustomEvent<ZitadelSignoutDetail>).detail);
    node.addEventListener('zitadel-continue', onContinueEvent);
    node.addEventListener('zitadel-signout', onSignoutEvent);
    return () => {
      node.removeEventListener('zitadel-continue', onContinueEvent);
      node.removeEventListener('zitadel-signout', onSignoutEvent);
    };
  });
</script>

<zitadel-session
  bind:this={el}
  {project}
  project-id={projectId}
  proxy-path={proxyPath}
  continue-url={continueUrl}
  post-sign-out-url={postSignOutUrl}
  {heading}
  continue-label={continueLabel}
  logout-label={logoutLabel}
></zitadel-session>

// packages/sdk-angular/src/lib/zitadel-session.component.ts
import type { ElementRef } from "@angular/core";
import type { ZitadelSession as ZitadelSessionElement } from "@zitadel/components";
import type { ZitadelContinueDetail, ZitadelSignoutDetail } from "@zitadel/sdk-core/types";

import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  EventEmitter,
  Input,
  Output,
  ViewChild,
} from "@angular/core";

import type { ZitadelProject } from "./config";

import "@zitadel/components";

/**
 * Angular wrapper for the `<zitadel-session>` Lit web component — the
 * post-sign-in "signed in as" card. See {@link ZitadelLoginComponent} for the
 * strategy. The widget's `zitadel-continue` and `zitadel-signout` events are
 * re-emitted with their detail as the `continue` and `signout` outputs. The
 * underlying `<zitadel-session>` custom element is exposed via the
 * {@link element} getter.
 *
 * ```html
 * <zitadel-auth-session [project]="project" continueUrl="/" postSignOutUrl="/login"
 *   (signout)="onSignout($event)" />
 * ```
 */
@Component({
  selector: "zitadel-auth-session",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<zitadel-session
    #el
    [project]="project"
    [projectId]="projectId"
    [proxyPath]="proxyPath"
    [attr.continue-url]="continueUrl"
    [attr.post-sign-out-url]="postSignOutUrl"
    [attr.heading]="heading"
    [attr.continue-label]="continueLabel"
    [attr.logout-label]="logoutLabel"
    (zitadel-continue)="onContinue($event)"
    (zitadel-signout)="onSignout($event)"
  ></zitadel-session>`,
})
export class ZitadelSessionComponent {
  @Input() project?: ZitadelProject;
  @Input() projectId?: string;
  @Input() proxyPath?: string;
  @Input() continueUrl?: string;
  @Input() postSignOutUrl?: string;
  @Input() heading?: string;
  @Input() continueLabel?: string;
  @Input() logoutLabel?: string;
  @Output() continue = new EventEmitter<ZitadelContinueDetail>();
  @Output() signout = new EventEmitter<ZitadelSignoutDetail>();

  @ViewChild("el") private elementRef?: ElementRef<ZitadelSessionElement>;

  /** The underlying `<zitadel-session>` custom element, or `null` before view init. */
  get element(): ZitadelSessionElement | null {
    return this.elementRef?.nativeElement ?? null;
  }

  onContinue(event: Event): void {
    this.continue.emit((event as CustomEvent<ZitadelContinueDetail>).detail);
  }

  onSignout(event: Event): void {
    this.signout.emit((event as CustomEvent<ZitadelSignoutDetail>).detail);
  }
}
