// packages/sdk-angular/src/lib/zitadel-login.component.ts
import type {
  ZitadelFlowCompleteDetail,
  ZitadelFlowErrorDetail,
  ZitadelFlowInputDetail,
  ZitadelFlowStepDetail,
} from '@zitadel/sdk-core/types';

import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';

import type { ZitadelProject } from './config';

// Registers <zitadel-login> / <zitadel-logout> with the browser.
import '@zitadel/components';

/**
 * Angular wrapper for the `<zitadel-login>` Lit web component.
 *
 * Uses a distinct selector (`zitadel-auth-login`) and renders the real custom
 * element in its template under `CUSTOM_ELEMENTS_SCHEMA`. The `project` handle
 * (from `configureZitadel(...)`) is bound as a DOM **property** via `[project]`;
 * `purpose` / `post-sign-in-url` are bound as attributes the Lit element reads.
 * The widget's `zitadel-*` events are re-emitted with their detail as the
 * `flowStep` / `flowInput` / `flowComplete` / `flowError` outputs.
 *
 * ```html
 * <zitadel-auth-login [project]="project" purpose="login" postSignInUrl="/"
 *   (flowComplete)="onComplete($event)" />
 * ```
 */
@Component({
  selector: 'zitadel-auth-login',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<zitadel-login
    [project]="project"
    [attr.purpose]="purpose"
    [attr.post-sign-in-url]="postSignInUrl"
    (zitadel-flow-step)="onFlowStep($event)"
    (zitadel-flow-input)="onFlowInput($event)"
    (zitadel-flow-complete)="onFlowComplete($event)"
    (zitadel-flow-error)="onFlowError($event)"
  ></zitadel-login>`,
})
export class ZitadelLoginComponent {
  @Input() project?: ZitadelProject;
  @Input() purpose = 'login';
  @Input() postSignInUrl?: string;
  @Output() flowStep = new EventEmitter<ZitadelFlowStepDetail>();
  @Output() flowInput = new EventEmitter<ZitadelFlowInputDetail>();
  @Output() flowComplete = new EventEmitter<ZitadelFlowCompleteDetail>();
  @Output() flowError = new EventEmitter<ZitadelFlowErrorDetail>();

  onFlowStep(event: Event): void {
    this.flowStep.emit((event as CustomEvent<ZitadelFlowStepDetail>).detail);
  }

  onFlowInput(event: Event): void {
    this.flowInput.emit((event as CustomEvent<ZitadelFlowInputDetail>).detail);
  }

  onFlowComplete(event: Event): void {
    this.flowComplete.emit(
      (event as CustomEvent<ZitadelFlowCompleteDetail>).detail,
    );
  }

  onFlowError(event: Event): void {
    this.flowError.emit((event as CustomEvent<ZitadelFlowErrorDetail>).detail);
  }
}

// packages/sdk-svelte/src/lib/ZitadelLogin.svelte
<script lang="ts">
  import '@zitadel/components'; // registers <zitadel-login>
  import type { ZitadelProject } from '@zitadel/api/config';

  import type {
    ZitadelFlowCompleteDetail,
    ZitadelFlowErrorDetail,
    ZitadelFlowInputDetail,
    ZitadelFlowStepDetail,
  } from './types';

  let {
    project,
    purpose = 'login',
    postSignInUrl,
    onFlowStep,
    onFlowInput,
    onFlowComplete,
    onFlowError,
  }: {
    project: ZitadelProject;
    purpose?: string;
    postSignInUrl?: string;
    onFlowStep?: (detail: ZitadelFlowStepDetail) => void;
    onFlowInput?: (detail: ZitadelFlowInputDetail) => void;
    onFlowComplete?: (detail: ZitadelFlowCompleteDetail) => void;
    onFlowError?: (detail: ZitadelFlowErrorDetail) => void;
  } = $props();

  let el: HTMLElement | undefined = $state();

  // object handle → DOM property (timing-proof, set after mount)
  $effect(() => {
    if (el) (el as unknown as { project?: ZitadelProject }).project = project;
  });

  // zitadel-* custom events → optional callbacks, with cleanup
  $effect(() => {
    if (!el) return;
    const step = (e: Event) => onFlowStep?.((e as CustomEvent<ZitadelFlowStepDetail>).detail);
    const input = (e: Event) => onFlowInput?.((e as CustomEvent<ZitadelFlowInputDetail>).detail);
    const done = (e: Event) => onFlowComplete?.((e as CustomEvent<ZitadelFlowCompleteDetail>).detail);
    const err = (e: Event) => onFlowError?.((e as CustomEvent<ZitadelFlowErrorDetail>).detail);
    el.addEventListener('zitadel-flow-step', step);
    el.addEventListener('zitadel-flow-input', input);
    el.addEventListener('zitadel-flow-complete', done);
    el.addEventListener('zitadel-flow-error', err);
    return () => {
      el?.removeEventListener('zitadel-flow-step', step);
      el?.removeEventListener('zitadel-flow-input', input);
      el?.removeEventListener('zitadel-flow-complete', done);
      el?.removeEventListener('zitadel-flow-error', err);
    };
  });
</script>

<zitadel-login bind:this={el} {purpose} post-sign-in-url={postSignInUrl}></zitadel-login>
