// apps/demo-nuxt/pages/admin.vue
<template>
  <main style="padding: 48px; max-width: 600px; margin: 0 auto">
    <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 24px">
      <h1 style="font-size: 24px; font-weight: 700; margin: 0">Admin</h1>
      <ClientOnly>
        <nextgen-logout proxy-base="/__nextgen" post-sign-out-url="/login" />
      </ClientOnly>
    </div>
    <p style="color: #6b7280">
      Signed in as {{ auth?.isAuthenticated ? auth.session.email : "unknown" }}
    </p>
  </main>
</template>

<script setup lang="ts">
import "@nextgen/ui-lit";
import type { ClientAuthResult } from "@nextgen/sdk-nuxt";

const auth = useState<ClientAuthResult>("nextgen-auth");
</script>

// apps/demo-next/src/app/admin/page.tsx
import { auth } from "@zitadel-nextgen/sdk-next/server";
import { LogoutWidget } from "./widget";

export default async function AdminPage() {
  const session = await auth();

  return (
    <main style={{ padding: "48px", maxWidth: "600px", margin: "0 auto" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "24px" }}>
        <h1 style={{ fontSize: "24px", fontWeight: 700, margin: 0 }}>Admin</h1>
        <LogoutWidget />
      </div>
      <p style={{ color: "#6b7280" }}>
        Signed in as {session.isAuthenticated ? session.session.email : "unknown"}
      </p>
    </main>
  );
}
