// apps/demo-next/src/app/login/page.tsx
import { auth } from "@zitadel-nextgen/sdk-next/server";
import { redirect } from "next/navigation";
import { LoginWidget } from "./widget";

export default async function LoginPage() {
  const session = await auth();
  if (session.isAuthenticated) redirect("/admin");
  return (
    <main
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "#f3f4f6",
      }}
    >
      <LoginWidget />
    </main>
  );
}

// apps/demo-nuxt/pages/login.vue
<template>
  <main
    style="
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background: #f3f4f6;
    "
  >
    <ClientOnly>
      <zitadel-login
        :project="project"
        post-sign-in-url="/admin"
      />
    </ClientOnly>
  </main>
</template>

<script setup lang="ts">
import type { ClientAuthResult } from "@zitadel/sdk-nuxt";
import { useZitadelProject } from "@zitadel/sdk-nuxt";

const auth = useState<ClientAuthResult>("nextgen-auth");
if (auth.value?.isAuthenticated) {
  await navigateTo("/admin");
}

const project = useZitadelProject();
</script>
