// packages/sdk-solid/src/index.tsx
import type { JSX } from 'solid-js';

// Registers <zitadel-login> / <zitadel-logout> with the browser, before render,
// so Solid binds `project` as a DOM property on an upgraded element.
import '@zitadel/components';
import {
  configureZitadel,
  getApi,
  getZitadelConfig,
  type ZitadelConfig,
  type ZitadelProject,
} from '@zitadel/api/config';

type FlowEvent = CustomEvent<unknown>;

// Teach Solid's JSX about the elements, the explicit `project` property, and the
// `zitadel-flow-*` custom events (prop:/on: keys declared directly so the
// declaration build is self-contained).
declare module 'solid-js' {
  // Solid exposes its JSX types through the `JSX` namespace; reopening it is the
  // only way to register custom elements + their prop:/on: keys.
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      'zitadel-login': HTMLAttributes<HTMLElement> & {
        'prop:project'?: ZitadelProject;
        purpose?: string;
        'post-sign-in-url'?: string;
        'on:zitadel-flow-step'?: (event: FlowEvent) => void;
        'on:zitadel-flow-complete'?: (event: FlowEvent) => void;
        'on:zitadel-flow-error'?: (event: FlowEvent) => void;
      };
      'zitadel-logout': HTMLAttributes<HTMLElement> & {
        'prop:project'?: ZitadelProject;
        'post-sign-out-url'?: string;
      };
    }
  }
}

export { configureZitadel, getApi, getZitadelConfig };
export type { ZitadelConfig, ZitadelProject };
export * from './types';

export interface ZitadelLoginProps {
  project: ZitadelProject;
  purpose?: string;
  postSignInUrl?: string;
  onFlowStep?: (detail: unknown) => void;
  onFlowComplete?: (detail: unknown) => void;
  onFlowError?: (detail: unknown) => void;
}

/**
 * Solid wrapper for the `<zitadel-login>` Lit web component. Binds the SDK
 * `project` handle as a DOM *property* via Solid's `prop:` namespace, and
 * surfaces the widget's `zitadel-flow-*` events as optional callbacks.
 */
export function ZitadelLogin(props: ZitadelLoginProps): JSX.Element {
  return (
    <zitadel-login
      prop:project={props.project}
      purpose={props.purpose ?? 'login'}
      post-sign-in-url={props.postSignInUrl}
      on:zitadel-flow-step={(event) => props.onFlowStep?.(event.detail)}
      on:zitadel-flow-complete={(event) => props.onFlowComplete?.(event.detail)}
      on:zitadel-flow-error={(event) => props.onFlowError?.(event.detail)}
    />
  );
}

export interface ZitadelLogoutProps {
  project: ZitadelProject;
  postSignOutUrl?: string;
}

/** Solid wrapper for the `<zitadel-logout>` Lit web component. */
export function ZitadelLogout(props: ZitadelLogoutProps): JSX.Element {
  return (
    <zitadel-logout
      prop:project={props.project}
      post-sign-out-url={props.postSignOutUrl}
    />
  );
}

// packages/sdk-qwik/src/index.tsx
import type { CreateFlowBodyPurpose } from '@zitadel/api/generated/model';

import {
  component$,
  useSignal,
  useVisibleTask$,
  type QRL,
} from '@builder.io/qwik';
import {
  configureZitadel,
  getApi,
  getZitadelConfig,
  type ZitadelConfig,
  type ZitadelProject,
} from '@zitadel/api/config';
// Registers <zitadel-login> / <zitadel-logout> with the browser, before render.
import '@zitadel/components';

export { configureZitadel, getApi, getZitadelConfig };
export type { ZitadelConfig, ZitadelProject };
export * from './types';

// `@zitadel/components` ships Qwik JSX types for the elements but omits the
// property-only `project` member (it has `attribute: false`). Qwik binds objects
// to custom elements as DOM *properties*, so we set it via a spread.
function projectProp(project: ZitadelProject): Record<string, unknown> {
  return { project };
}

export interface ZitadelLoginProps {
  project: ZitadelProject;
  purpose?: CreateFlowBodyPurpose;
  postSignInUrl?: string;
  onFlowStep$?: QRL<(detail: unknown) => void>;
  onFlowComplete$?: QRL<(detail: unknown) => void>;
  onFlowError$?: QRL<(detail: unknown) => void>;
}

/**
 * Qwik wrapper for the `<zitadel-login>` Lit web component. Binds the SDK
 * `project` handle as a DOM property (Qwik passes objects to custom elements as
 * properties), and surfaces the widget's `zitadel-flow-*` events as optional
 * callbacks. `useVisibleTask$` is the documented escape hatch for wiring native
 * listeners on a third-party element; Qwik's declarative `useOn` does not catch
 * these programmatic custom events.
 */
export const ZitadelLogin = component$<ZitadelLoginProps>((props) => {
  const host = useSignal<HTMLElement>();
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ track, cleanup }) => {
    const el = track(() => host.value);
    if (!el) return;
    const onStep = (e: Event) =>
      void props.onFlowStep$?.((e as CustomEvent).detail);
    const onComplete = (e: Event) =>
      void props.onFlowComplete$?.((e as CustomEvent).detail);
    const onError = (e: Event) =>
      void props.onFlowError$?.((e as CustomEvent).detail);
    el.addEventListener('zitadel-flow-step', onStep);
    el.addEventListener('zitadel-flow-complete', onComplete);
    el.addEventListener('zitadel-flow-error', onError);
    cleanup(() => {
      el.removeEventListener('zitadel-flow-step', onStep);
      el.removeEventListener('zitadel-flow-complete', onComplete);
      el.removeEventListener('zitadel-flow-error', onError);
    });
  });
  return (
    <zitadel-login
      ref={host}
      {...projectProp(props.project)}
      purpose={props.purpose ?? 'login'}
      post-sign-in-url={props.postSignInUrl}
    />
  );
});

export interface ZitadelLogoutProps {
  project: ZitadelProject;
  postSignOutUrl?: string;
}

/** Qwik wrapper for the `<zitadel-logout>` Lit web component. */
export const ZitadelLogout = component$<ZitadelLogoutProps>((props) => {
  return (
    <zitadel-logout
      {...projectProp(props.project)}
      post-sign-out-url={props.postSignOutUrl}
    />
  );
});
